---
title: "New"
output: html_document
---
```{r}
library(tidyverse) # for various packages
library(haven) #for read_csv
library(survRM2) #For RMST
library(magrittr) #For %$%
library(VIM) 
library(mice) 
library(lattice)
library(MASS)
poverty <- read_csv("Poverty.csv") 

```
```{r, eval=FALSE}
glm.RR <- function(GLM.RESULT, digits = 2) {

    if (GLM.RESULT$family$family == "binomial") {
        LABEL <- "OR"
    } else if (GLM.RESULT$family$family == "poisson") {
        LABEL <- "RR"
    } else {
        stop("Not logistic or Poisson model")
    }

    COEF      <- stats::coef(GLM.RESULT)
    CONFINT   <- stats::confint(GLM.RESULT)
    TABLE     <- cbind(coef=COEF, CONFINT)
    TABLE.EXP <- round(exp(TABLE), digits)

    colnames(TABLE.EXP)[1] <- LABEL

    TABLE.EXP
}
```



```{r}
names(poverty)<-c("zipcode","population","bpoverty","bpoverty%","casecount","casepercent","caserate")
md.pattern(poverty, rotate.names=TRUE)
poverty <-na.omit(poverty)
poverty <- poverty %>%
         ##Recode stage variable as a binary variable
  mutate(poverty_stage=case_when(zipcode %in% c("63119","63117","63109","63102","63123","63105","63125","63139","63143") ~ 0,
                                 zipcode %in% 
c("63110","63130","63101","63103","63104","63116","63112","63137","63136") ~ 1,
                                 zipcode %in% 
c("63108","63147","63118","63113","63115","63111","63107","63120","63106") ~ 2),
poverty_stage = factor(poverty_stage, 0:2, c("low", "medium", "high")))


```

```{r}

fit <- glm(casecount ~ poverty_stage, offset = log(population), family = poisson(), data = poverty)
summary(fit)
exp(coef(fit))
glm.RR(fit)
```


```{r}
c(mean(poverty$casecount),var(poverty$casecount))
#variance >> mean
```




```{r}
# Run negative binomial
fit2 <- glm.nb(casecount ~ poverty_stage+offset(log(population)), ,data = poverty)
summary(fit2)
exp(coef(fit2))

```

